# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hsar_cpp_arma <- function(X, y, W, M, Z, detval, detvalM, Unum, burnin, Nsim, thinning, rho_start, lambda_start, sigma2e_start, sigma2u_start, betas_start) {
    .Call('HSAR_hsar_cpp_arma', PACKAGE = 'HSAR', X, y, W, M, Z, detval, detvalM, Unum, burnin, Nsim, thinning, rho_start, lambda_start, sigma2e_start, sigma2u_start, betas_start)
}

hsar_cpp_arma_lambda_0 <- function(X, y, W, Z, detval, Unum, burnin, Nsim, thinning, rho_start, sigma2e_start, sigma2u_start, betas_start) {
    .Call('HSAR_hsar_cpp_arma_lambda_0', PACKAGE = 'HSAR', X, y, W, Z, detval, Unum, burnin, Nsim, thinning, rho_start, sigma2e_start, sigma2u_start, betas_start)
}

hsar_cpp_arma_rho_0 <- function(X, y, M, Z, detvalM, Unum, burnin, Nsim, thinning, lambda_start, sigma2e_start, sigma2u_start, betas_start) {
    .Call('HSAR_hsar_cpp_arma_rho_0', PACKAGE = 'HSAR', X, y, M, Z, detvalM, Unum, burnin, Nsim, thinning, lambda_start, sigma2e_start, sigma2u_start, betas_start)
}

sar_cpp_arma <- function(X, y, W, detval, burnin, Nsim, thinning, rho_start, sigma2e_start, betas_start) {
    .Call('HSAR_sar_cpp_arma', PACKAGE = 'HSAR', X, y, W, detval, burnin, Nsim, thinning, rho_start, sigma2e_start, betas_start)
}

